### ISSUE TITLE
Checklist email for what to bring to HackNYU

### ISSUE THREAD

**Issue by themichaelyang** [hacknyu/website#118]
Also include: info about getting there, schedule, etc

## Checklist
- Student ID / Gov't issued ID (with photo); must match name 
- Update form to make sure it is accurate (emergency contact, etc)
- Sleeping bag if planning on sleeping
- Toiletries (if planning on being not gross)
- Towel and change of clothes if planning on showering (this is a good idea)
- Any medication (epipens!)
- Phone (if you have one)
- Laptop
- Charger
- if under 18, waiver form (otherwise you will be turned away)

**Comment by stefancherubin** [comment]
Also, reusable water bottles or coffee mugs

**Comment by NicholasLYang** [comment]
Sleeping mask and earplugs are good. I'd recommend emergen-c (makes you feel not shit after no sleep) and mechanical keyboard (to piss off people with your typing noise). Comfortable shoes and warm jacket (hackathon venues get cold)
