### ISSUE TITLE
Logistics Email for admitted

### ISSUE THREAD

**Issue by makertech81** [hacknyu/website#120]
As detailed in this useful site [here](https://hackathon.guide/), scroll down and find the recommendation of a logistics email.  Might be useful in addition or with the checklist for those admitted. Like a reminder email that they are signed up and where to go and stuff, accessibility, and schedule like that all in one nice email.  I know you have the info on the site, might be useful though.

**Comment by themichaelyang** [comment]
Thanks for the suggestion! This issue has already been opened: #118
