### ISSUE TITLE
Minor SchoolsInput bugs

### ISSUE THREAD

**Issue by NicholasLYang** [hacknyu/website#31]
I suppose this is preference, so feel free to provide your own opinion, but I'd prefer that when a user clicks an option, it closes the autocomplete menu instead of keeping it open with just that one option. Also, the menu stays there as a tiny little rectangle even when the field is blank. We should probably just not render it 
<img width="458" alt="screen shot 2018-12-23 at 2 04 17 pm" src="https://user-images.githubusercontent.com/7357863/50386791-b2354f80-06bb-11e9-8ae9-003cd44e2bdc.png">
<img width="613" alt="screen shot 2018-12-23 at 2 05 05 pm" src="https://user-images.githubusercontent.com/7357863/50386798-c11c0200-06bb-11e9-9da2-217579e1c067.png">

**Comment by pierreTklein** [comment]
Hey! 
Just wanted to give you a heads up that on Chrome, the school dropdown has no overflow, and causes this: 
[![Image from Gyazo](https://i.gyazo.com/ae3b7ae7b5c1aab4879f938c81dcdc1d.gif)](https://gyazo.com/ae3b7ae7b5c1aab4879f938c81dcdc1d)

**Comment by NicholasLYang** [comment]
Haha yeah that's not great. We'll fix that
