### ISSUE TITLE
Resume upload should give timestamp as feedback

### ISSUE THREAD

**Issue by themichaelyang** [hacknyu/website#45]
Currently a correctly / incorrectly uploaded resume are indistinguishable on first upload.

Timestamp is added only on page reload.

**Comment by themichaelyang** [comment]
is this resolved?

**Comment by themichaelyang** [comment]
But does it update the resume timestamp without reload?

**Comment by stefancherubin** [comment]
Yup, I verified that a few hours ago

**Comment by NicholasLYang** [comment]
Yeah I fixed this when I migrated all of the ApplyPage state to redux

**Comment by themichaelyang** [comment]
oh nice! closing this
